title: HuanHH Curriculum Vitae
author: HuanHH
email: huanhh1911@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is demo create a Curriculum Vitae by Github page

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
